### Question 1

Use the techniques you learned in class to solve this problem.

(a) Zoo Animal Classification data set will be used in this problem. Load the data set from below link.<br>
https://www.kaggle.com/uciml/zoo-animal-classification

In [19]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, LabelEncoder


zoo_data = pd.read_csv("zoo.csv")
zoo_data_encoded = zoo_data

LabelEncoder_X= LabelEncoder()
zoo_data_encoded['animal_name']= LabelEncoder_X.fit_transform(zoo_data_encoded['animal_name'])
zoo_data_encoded

#Turn categorical data into quantitative data

animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0              0     1         0     0     1         0        0         1   
1              1     1         0     0     1         0        0         0   
2              2     0         0     1     0         0        1         1   
3              3     1         0     0     1         0        0         1   
4              4     1         0     0     1         0        0         1   
..           ...   ...       ...   ...   ...       ...      ...       ...   
96            95     1         0     0     1         0        0         0   
97            96     1         0     1     0         1        0         0   
98            97     1         0     0     1         0        0         1   
99            98     0         0     1     0         0        0         0   
100           99     0         1     1     0         1        0         0   

     toothed  backbone  breathes  venomous  fins  legs  tail  domestic  \
0          1         1         1         0     0     4     0         0   
1          1         1         1         0     0     4     1         0   
2          1         1         0         0     1     0     1         0   
3          1         1         1         0     0     4     0         0   
4          1         1         1         0     0     4     1         0   
..       ...       ...       ...       ...   ...   ...   ...       ...   
96         1         1         1         0     0     2     1         0   
97         0         0         1         1     0     6     0         0   
98         1         1         1         0     0     4     1         0   
99         0         0         1         0     0     0     0         0   
100        0         1         1         0     0     2     1         0   

     catsize  class_type  
0          1           1  
1          1           1  
2          0           4  
3          1           1  
4          1           1  
..       ...         ...  
96         1           1  
97         0           6  
98         1           1  
99         0           7  
100        0           2  

[101 rows x 18 columns]

(b) List target names and feature names of Zoo Animal Classification dataset.

In [20]:
zoo_data_encoded.dtypes

animal_name    int64
hair           int64
feathers       int64
eggs           int64
milk           int64
airborne       int64
aquatic        int64
predator       int64
toothed        int64
backbone       int64
breathes       int64
venomous       int64
fins           int64
legs           int64
tail           int64
domestic       int64
catsize        int64
class_type     int64
dtype: object

(c) Split your data using model selection.train test split to 80% training data and 20% test data.

In [21]:
from sklearn.model_selection import train_test_split
x_feature_data = zoo_data_encoded.iloc[:, zoo_data.columns != "class_type"]
y_target_data = zoo_data_encoded.iloc[:, zoo_data.columns == "class_type"]

X_train, X_test, y_train, y_test = train_test_split(x_feature_data, y_target_data, test_size = 0.20, random_state = 1)

print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(80, 17)
(80, 1)
(21, 17)
(21, 1)


(d)  Use appropriate model and train with the training data set. Test your trained model on the test data set and classify the values of the samples in the test data set.

In [22]:
#logistic regression
from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression(max_iter=1000)
logistic_model.fit(X_train, y_train) 

predictions_of_logistic_regression = logistic_model.predict(X_test)
print(predictions_of_logistic_regression)

/Users/prabjyot/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


[1 2 1 2 1 7 1 2 4 5 2 1 1 1 1 1 1 1 7 3 2]


(f) Calculate the accuracy and plot Confusion Matrix.
 <br>

In [26]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix as cm

print(accuracy_score(y_test, predictions_of_logistic_regression))


confusion_matrix = cm(y_test, predictions_of_logistic_regression)
print(confusion_matrix)

1.0
[[11  0  0  0  0  0]
 [ 0  5  0  0  0  0]
 [ 0  0  1  0  0  0]
 [ 0  0  0  1  0  0]
 [ 0  0  0  0  1  0]
 [ 0  0  0  0  0  2]]


(e) Write your comments about the confusion matrix of your experiment.

In [6]:
#I believe that the diagnoal values that are the true positive values, which makes this confusion matrix 
#nice and easy to interpret. 
#For class 1 there were 11 true positives, for class 2 there were 5 true positives, and so on and so forth for the
#classes along the diagonal itself. I thought my understanding was wrong because I didnt realize the accuracy was 
#100%

#Initially I was confused and had to reference this just to make sure I wasn't crazy: 
#https://www.youtube.com/watch?v=FAr2GmWNbT0&ab_channel=NoureddinSadawi

### Question 2

The handwritten digit data set MNIST is a subset of NIST, which can be used for simple implementation of machine learning algorithms. In this problem, you will use support vector machine to finish the classification of MNIST. <br>
https://www.kaggle.com/c/digit-recognizer/data

(a) Load the first 10K samples from "train.csv" and split them into training and testing data by 0.2. Use sklearn.svm to train a model with raw pixel features. Choose the linear kernel and set C = 5 and gamma= 0.05. Report the model.

In [7]:
digit_train_data = pd.read_csv("train.csv",  nrows=10000)
x_data_digit_train_data = digit_train_data.iloc[:, digit_train_data.columns != "label"]
y_data_digit_train_data = digit_train_data.iloc[:, digit_train_data.columns == "label"]

print(x_data_digit_train_data.shape)
print(y_data_digit_train_data.shape)

(10000, 784)
(10000, 1)


In [8]:
X_train, X_test, y_train, y_test = train_test_split(x_data_digit_train_data, y_data_digit_train_data, test_size = 0.2, random_state = 1)



In [9]:
from sklearn import svm
svm_model = svm.SVC(kernel='linear', C = 5, gamma= 0.05) # Linear Kernel

#Train the model using the training sets
svm_model.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = svm_model.predict(X_test)

/Users/prabjyot/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [10]:
print("Accuracy:",accuracy_score(y_test, y_pred))


Accuracy: 0.9055


(b) How many support vectors does each class have? List the support vectors for each class and test the prediction accuracy by metrics.classification report.

In [11]:
from sklearn import metrics
#https://scikit-learn.org/stable/modules/svm.html
print("Support vector for each class: ",svm_model.n_support_, "\n")

print("Classification Report: \n",metrics.classification_report(y_test, y_pred))

Support vector for each class:  [166 132 236 260 229 314 174 208 287 258] 

Classification Report: 
               precision    recall  f1-score   support

           0       0.97      0.98      0.97       205
           1       0.91      0.97      0.94       196
           2       0.87      0.95      0.91       227
           3       0.89      0.88      0.89       206
           4       0.90      0.92      0.91       201
           5       0.85      0.88      0.87       157
           6       0.96      0.95      0.95       207
           7       0.93      0.90      0.92       221
           8       0.91      0.79      0.85       184
           9       0.86      0.81      0.83       196

    accuracy                           0.91      2000
   macro avg       0.90      0.90      0.90      2000
weighted avg       0.91      0.91      0.90      2000



(c) Repeat (a) and (b) with a RBF kernel and the same C and gamma.

In [12]:
svm_model_rbf = svm.SVC(kernel='rbf', C = 5, gamma= 0.05) # Linear Kernel

#Train the model using the training sets
svm_model_rbf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred_rbf = svm_model_rbf.predict(X_test)

/Users/prabjyot/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [13]:
print("Accuracy:",accuracy_score(y_test, y_pred_rbf))


Accuracy: 0.098


In [14]:
print("Support vector for each class: ",svm_model_rbf.n_support_, "\n")

print("Classification Report: \n",metrics.classification_report(y_test, y_pred_rbf))

Support vector for each class:  [786 899 818 803 766 749 796 818 766 799] 

Classification Report: 
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       205
           1       0.10      1.00      0.18       196
           2       0.00      0.00      0.00       227
           3       0.00      0.00      0.00       206
           4       0.00      0.00      0.00       201
           5       0.00      0.00      0.00       157
           6       0.00      0.00      0.00       207
           7       0.00      0.00      0.00       221
           8       0.00      0.00      0.00       184
           9       0.00      0.00      0.00       196

    accuracy                           0.10      2000
   macro avg       0.01      0.10      0.02      2000
weighted avg       0.01      0.10      0.02      2000



/Users/prabjyot/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/prabjyot/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/prabjyot/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(d) Compare the two models and comment on the results.

In [15]:
#The SVM model with the kernel based on rbf was much worse than the SVM model with the linear kernel
#Comparing precision, recall, f1 score, and accuracy between the two different kernels, we can see that 
#the linear kernel is a far better model for this situation. 

#I was curious as to why the results were so different when the model was the same apart from one parameter
#https://www.kdnuggets.com/2016/06/select-support-vector-machine-kernels.html
#This link explained that the linear kernel is far more helpful when the data is easily linearly classifiable,
#but the when rbf is applied to a linearly separable dataset, the quality of the results could drop
#Essentially, when the datapoints are more circular/cyclical/surrounded youd want to employ an rbf kernel as opposed
#to a linear kernel.